import type { RareDiseasePreset } from "./types";

export const rareDiseasePresets: RareDiseasePreset[] = [
  { id: "eds", nameZh: "埃勒斯-当洛斯综合征", nameEn: "Ehlers-Danlos syndrome", category: "connective-tissue", orphaCode: "ORPHA:98249" },
  { id: "hht", nameZh: "遗传性出血性毛细血管扩张症", nameEn: "Hereditary hemorrhagic telangiectasia", category: "vascular", orphaCode: "ORPHA:774" },
  { id: "pompe", nameZh: "庞贝病", nameEn: "Pompe disease", category: "metabolic", orphaCode: "ORPHA:365" },
  { id: "fabry", nameZh: "法布雷病", nameEn: "Fabry disease", category: "metabolic", orphaCode: "ORPHA:324" },
  { id: "gaucher", nameZh: "戈谢病", nameEn: "Gaucher disease", category: "metabolic", orphaCode: "ORPHA:355" },
  { id: "pku", nameZh: "苯丙酮尿症", nameEn: "Phenylketonuria", category: "metabolic", orphaCode: "ORPHA:716" },
  { id: "als", nameZh: "肌萎缩侧索硬化", nameEn: "Amyotrophic lateral sclerosis", category: "neurology", orphaCode: "ORPHA:803" },
  { id: "huntington", nameZh: "亨廷顿病", nameEn: "Huntington disease", category: "neurology", orphaCode: "ORPHA:399" },
  { id: "sma", nameZh: "脊髓性肌萎缩症", nameEn: "Spinal muscular atrophy", category: "neurology", orphaCode: "ORPHA:70" },
  { id: "dmd", nameZh: "杜氏肌营养不良", nameEn: "Duchenne muscular dystrophy", category: "neuromuscular", orphaCode: "ORPHA:98896" },
  { id: "myasthenia", nameZh: "重症肌无力", nameEn: "Myasthenia gravis", category: "neuromuscular", orphaCode: "ORPHA:589" },
  { id: "cystic-fibrosis", nameZh: "囊性纤维化", nameEn: "Cystic fibrosis", category: "pulmonary", orphaCode: "ORPHA:586" },
  { id: "pah", nameZh: "肺动脉高压", nameEn: "Pulmonary arterial hypertension", category: "cardiopulmonary", orphaCode: "ORPHA:182090" },
  { id: "long-qt", nameZh: "长QT综合征", nameEn: "Long QT syndrome", category: "cardiology", orphaCode: "ORPHA:768" },
  { id: "brugada", nameZh: "Brugada综合征", nameEn: "Brugada syndrome", category: "cardiology", orphaCode: "ORPHA:130" },
  { id: "marfan", nameZh: "马凡综合征", nameEn: "Marfan syndrome", category: "connective-tissue", orphaCode: "ORPHA:558" },
  { id: "nf1", nameZh: "1型神经纤维瘤病", nameEn: "Neurofibromatosis type 1", category: "genetic", orphaCode: "ORPHA:636" },
  { id: "tuberous-sclerosis", nameZh: "结节性硬化症", nameEn: "Tuberous sclerosis complex", category: "genetic", orphaCode: "ORPHA:805" },
  { id: "wilson", nameZh: "威尔逊病", nameEn: "Wilson disease", category: "metabolic", orphaCode: "ORPHA:905" },
  { id: "porphyria", nameZh: "急性卟啉病", nameEn: "Acute porphyria", category: "metabolic", orphaCode: "ORPHA:95157" },
  { id: "scid", nameZh: "重症联合免疫缺陷", nameEn: "Severe combined immunodeficiency", category: "immunology", orphaCode: "ORPHA:183660" },
  { id: "aicardi", nameZh: "Aicardi综合征", nameEn: "Aicardi syndrome", category: "neurology", orphaCode: "ORPHA:50" },
  { id: "rett", nameZh: "Rett综合征", nameEn: "Rett syndrome", category: "neurology", orphaCode: "ORPHA:778" },
  { id: "prader-willi", nameZh: "普拉德-威利综合征", nameEn: "Prader-Willi syndrome", category: "genetic", orphaCode: "ORPHA:739" },
  { id: "angelman", nameZh: "Angelman综合征", nameEn: "Angelman syndrome", category: "genetic", orphaCode: "ORPHA:72" },
  { id: "turner", nameZh: "特纳综合征", nameEn: "Turner syndrome", category: "chromosomal", orphaCode: "ORPHA:881" },
  { id: "noonan", nameZh: "Noonan综合征", nameEn: "Noonan syndrome", category: "genetic", orphaCode: "ORPHA:648" },
  { id: "mps", nameZh: "黏多糖贮积症", nameEn: "Mucopolysaccharidosis", category: "metabolic", orphaCode: "ORPHA:79256" },
  { id: "behcet", nameZh: "白塞病", nameEn: "Behcet disease", category: "autoimmune", orphaCode: "ORPHA:117" },
  { id: "vasculitis", nameZh: "ANCA相关性血管炎", nameEn: "ANCA-associated vasculitis", category: "autoimmune" }
];
